In [22]:
import numpy as np

In [25]:
a = [1, 2, 3]
b = np.array(a)
b

array([1, 2, 3])

In [35]:
a = [1, 2]
b = [3, 4]
e = [5, 6]
f = [7, 8]
c = np.array([a, b, e, f])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
c.shape

(4, 2)

In [37]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [43]:
c.dtype

dtype('float64')

In [38]:
c = np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
a = np.arange(1, 10, 1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.dtype

dtype('int64')

In [42]:
a.shape

(9,)