In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]
b = np.array(a)
b

array([1, 2, 3])

In [3]:
a = [1, 2]
b = [3, 4]
e = [5, 6]
f = [7, 8]
c = np.array([a, b, e, f])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
c.shape

(4, 2)

In [5]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [6]:
c.dtype

dtype('float64')

In [7]:
c = np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.arange(1, 10, 1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.dtype

dtype('int32')

In [11]:
a.shape

(9,)

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[3]

3

In [14]:
b = a[3:5]
b

array([3, 4])

In [15]:
c = [[1, 2, 3], [6, 7, 8]]
c[0][::-1]

[3, 2, 1]

In [16]:
a = np.arange(1, 5)
b = np.arange(6, 10)
c = a + b
c

array([ 7,  9, 11, 13])

In [20]:
a = np.array([2, 6, 12, 3, 6])
mean = a.mean()
mean

5.8

In [21]:
q = np.median(a)
q

6.0